# Generated by Django 4.2.4 on 2023-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('math_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('exercise', models.ManyToManyField(to='math_app.exercise')),
            ],
            options={
                'ordering': ('time_update',),
            },
        ),
    ]
