# Generated by Django 4.2.4 on 2024-05-02 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_examattempt_geometry_score_examattempt_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattempt',
            name='completed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
