# Generated by Django 4.2.4 on 2024-05-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0006_alter_answer_answer'),
        ('exam', '0003_alter_examattempt_completed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='tests',
        ),
        migrations.AddField(
            model_name='exam',
            name='exercises',
            field=models.ManyToManyField(to='math_app.exercise'),
        ),
    ]
