# Generated by Django 4.2.4 on 2024-05-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0006_alter_answer_answer'),
        ('exam', '0004_remove_exam_tests_exam_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exam',
            name='tests',
            field=models.ManyToManyField(to='math_app.test'),
        ),
    ]
