# Generated by Django 4.2.4 on 2024-05-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='users/default.jpg', null=True, upload_to='users/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
