# Generated by Django 4.2.4 on 2023-10-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('category',)},
        ),
        migrations.RemoveField(
            model_name='test',
            name='part2',
        ),
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='number',
            field=models.CharField(max_length=200, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Тип'),
        ),
    ]
