# Generated by Django 4.2.4 on 2023-10-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0002_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='image',
        ),
        migrations.AddField(
            model_name='test',
            name='image_problem_text',
            field=models.ImageField(blank=True, upload_to='images_problem_text/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='test',
            name='image_solution',
            field=models.ImageField(blank=True, upload_to='images_solution/%Y/%m/%d/'),
        ),
    ]
