# Generated by Django 4.2.4 on 2023-11-12 19:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0004_remove_test_image_problem_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('exercise__subcategory__category__id',)},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ответ'),
        ),
    ]
