# Generated by Django 4.2.4 on 2024-04-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0005_alter_test_options_alter_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Ответ'),
        ),
    ]
