# Generated by Django 4.2.4 on 2024-05-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0006_alter_answer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='part2',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
